# Generated by Django 4.0.2 on 2022-02-16 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likesong', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likesong', to='music.song')),
            ],
        ),
    ]
